### ISSUE TITLE
Cannot install NODAL

### ISSUE THREAD

**Issue by FloraPoon** [phrb/StochasticSearch.jl#31]
Pkg.add() does not work (and Pkg.update() as suggested does not help):
```julia> Pkg.add("NODAL")
ERROR: NODAL can't be installed because it has no versions that support 0.6.4 of julia. You may need to update METADATA by running
 `Pkg.update()`
```
Pkg.clone() gives the following warning
```
WARNING: julia is fixed at 0.6.4 conflicting with requirement for NODAL: [0.7.0-,∞)
```
Is it possible to fix this, or is NODAL.jl only intended for v0.7 and above?

**Comment by thvhauwe** [comment]
Having the same issue! Cannot install in version 0.6.4, 0.7 or 1.0

**Comment by phrb** [comment]
Hi, I'm now working on fixing this. Thanks for letting me know!

**Comment by phrb** [comment]
I've updated the package for Julia **v1.0**, and it's already at the official repositories. You should be able to install it using `Pkg.add()`. Note that I've dropped support for older Julia versions.
