### ISSUE TITLE
Update this repo to julia 1.0?

### ISSUE THREAD

**Issue by thvhauwe** [phrb/StochasticSearch.jl#32]
I am having the same issue as #31 , cannot install NODAL in 0.6 or 0.7
Maybe an update for NODAL to work with julia 1.0 is due?

**Comment by phrb** [comment]
Hi, thanks for letting me know!

The update is really due, I'll make it as soon as possible and I'll let you know.

**Comment by phrb** [comment]
Sorry for the delay, hope you're still interested. I've updated the package for Julia **v1.0**, and it's already at the official repositories. You should be able to install it using `Pkg.add()`. Note that I've dropped support for older Julia versions.

Please let me know if you have any issues using the package, I'll be happy to help!
